apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.13
      helm:
        releaseName: argocd
        valueFiles:
          - $h8s/ci-cd/argocd/environments/prod/values.yaml
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      ref: h8s
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      path: ci-cd/argocd/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
