ARG BUILD_USER=buildah
ARG BUILD_UID=1000
ARG BUILD_GID=1000

FROM harbor.okwilkins.dev/docker-hub-cache/nixos/nix:2.34.7 AS builder

ARG BUILD_USER
ARG BUILD_UID
ARG BUILD_GID

RUN mkdir -p /etc/nix && \
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf && \
    echo "sandbox = false" >> /etc/nix/nix.conf && \
    echo "filter-syscalls = false" >> /etc/nix/nix.conf && \
    echo "build-users-group =" >> /etc/nix/nix.conf

WORKDIR /tmp/build
COPY flake.nix flake.lock ./

RUN nix build .

RUN mkdir /tmp/nix-store-closure
RUN cp -R $(nix-store -qR result/) /tmp/nix-store-closure

RUN mkdir -p /tmp/etc
RUN echo "${BUILD_USER}:x:${BUILD_UID}:${BUILD_GID}:${BUILD_USER} container user:/home/${BUILD_USER}:/home/${BUILD_USER}/bin/sh" > /tmp/etc/passwd
RUN echo "${BUILD_USER}:x:${BUILD_GID}:" > /tmp/etc/group

RUN echo "${BUILD_USER}:100000:65536" > /etc/subuid \
 && echo "${BUILD_USER}:100000:65536" > /etc/subgid

RUN mkdir -p /tmp/home/${BUILD_USER}/.config/containers
RUN echo '[storage]' > /tmp/home/${BUILD_USER}/.config/containers/storage.conf && \
    echo 'driver = "vfs"' >> /tmp/home/${BUILD_USER}/.config/containers/storage.conf && \
    echo "runroot = \"/home/${BUILD_USER}/.local/share/containers/storage-run\"" >> /tmp/home/${BUILD_USER}/.config/containers/storage.conf && \
    echo "graphroot = \"/home/${BUILD_USER}/.local/share/containers/storage\"" >> /tmp/home/${BUILD_USER}/.config/containers/storage.conf && \
    echo '[storage.options.vfs]' >> /tmp/home/${BUILD_USER}/.config/containers/storage.conf && \
    echo 'ignore_chown_errors = "true"' >> /tmp/home/${BUILD_USER}/.config/containers/storage.conf

RUN mkdir -p /tmp/etc/containers && echo '{ "default": [ { "type": "insecureAcceptAnything" } ] }' > /tmp/etc/containers/policy.json


FROM scratch

ARG BUILD_USER
ARG BUILD_UID
ARG BUILD_GID

ENV PATH="/home/${BUILD_USER}/bin"
ENV _BUILDAH_STARTED_IN_USERNS=""
ENV BUILDAH_ISOLATION=chroot
ENV TMPDIR=/home/${BUILD_USER}/.local/share/containers/storage
ENV HOME=/home/${BUILD_USER}
ENV XDG_CONFIG_HOME=/home/${BUILD_USER}/.config
ENV XDG_RUNTIME_DIR=/home/${BUILD_USER}/.local/share/containers/storage-run

COPY --from=builder /tmp/etc/passwd /etc/passwd
COPY --from=builder /tmp/etc/group /etc/group
COPY --from=builder /tmp/home/${BUILD_USER} /home/${BUILD_USER}
COPY --from=builder /etc/subuid /etc/subuid
COPY --from=builder /etc/subgid /etc/subgid

COPY --from=builder /tmp/nix-store-closure /nix/store
COPY --from=builder /tmp/build/result/bin /home/${BUILD_USER}/bin
COPY --from=builder /tmp/build/result/bin/sh /bin/sh
COPY --from=builder /tmp/etc/containers /etc/containers
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

USER ${BUILD_UID}:${BUILD_GID}

