apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searxng-redis
  name: searxng-redis
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng-redis
  template:
    metadata:
      labels:
        app: searxng-redis
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: redis
          image: harbor.okwilkins.dev/docker-hub-cache/redis:8.6.3-alpine3.23
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
          volumeMounts:
            - mountPath: /usr/local/etc/redis
              name: redis-config
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: redis-config
          configMap:
            name: searxng-redis
