apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mazanoke
  name: mazanoke
  namespace: mazanoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mazanoke
  template:
    metadata:
      labels:
        app: mazanoke
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: mazanoke
          image: harbor.okwilkins.dev/ghcr-cache/civilblur/mazanoke:v1.1.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /var/run
              name: nginx-run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
